### ISSUE TITLE
Récap modifs

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/pollos-para-todos#10]
Les "?" en fin de phrase représentent des propositions, à toi de voir

- [x] faire les plaques des billets de 500 100 et 50
- [x] faire la ligne du bas pour les cartes de jeu
- [ ] faire le poulet
- [ ] les cartes Parti pourraient ête deux fois plus petite en longueur non?
- [ ] sur la map:
    - [x] souligner les nom des zones
   - [x] rajouter la légende pour les routes maritimes
   - [x] rajouter les jours (soit 1 2 3 4 5 6 7, soit L M M J V S D, soit Lu Ma Me Je Ve Sa Di)
   - [ ] mettre en logo sur la carte le poulet?
   - [x] mettre plus en valeur le texte "pollos para todos" sur la map?
   - [x] emplacement des cartes actions et évenement et emplacement de leurs défausse respective?

**Comment by LeonLenclos** [comment]
C'est pas bien que les cartes parti soient grandes ? pour poser les pions et le poulet?

**Comment by dracdrac** [comment]
ok

**Comment by dracdrac** [comment]
et pas besoin de mettre le poulet sur la map enfait, y'a assez de truc
sinon je valide touuuuut
eva aussi sauf le nom de l'ile (elle à pas d'autres proposition cette conne)

**Comment by LeonLenclos** [comment]
ok. ba sinon on peut ne pas mettre de nom pour l'île ?

**Comment by dracdrac** [comment]
Ben moi j'aime bien le petit bandeau que t'as fait
sinon: 
FUKUSHIMA
L'île aux Yenchs
L'île
L'île Pump

**Comment by LeonLenclos** [comment]
L’ile aux vampires ?
