### ISSUE TITLE
que dois comporter un boite de base?

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/pollos-para-todos#2]
Que comporte une boite de base?
combien de billets de 50, 100, 500?
Combien de pions, combien de couleurs différentes?
Quels dés? 20? 6? combien?

**Comment by LeonLenclos** [comment]
j'ai l'impression que le nombre de pions et de billets qu'il y a chez toi c'est pas mal. Peut etre un peu moins de 500 et plus de 100. 

Je dirai 6 couleurs de pions

Et un d20 ?

**Comment by dracdrac** [comment]
Chez moi il y a 
10 x 100c
30 x 50c

ça allait pour 4 mais 6 peut etre pas
du coup:
20x50
20x100
10x500
?

ok pour dé 20

**Comment by LeonLenclos** [comment]
et les pions ?

**Comment by dracdrac** [comment]
autour de 25-30 Ppar couleur

**Comment by dracdrac** [comment]
Donc si on part sur 6 couleurs de 30 pions, ça fait 180 pions
si on veux un truc simple genre ça: https://toutpourlejeu.com/fr/pions-de-jeux-et-jetons/2308-20-mini-octogones-8x15-mm-en-bois-colore-pour-jeu-0659436655041.html
ça reviens à 15 juste pour les pions. Donc je pense qu'il faut partir sur des pions à découper comme on à fait

**Comment by dracdrac** [comment]
bon sur des lots déjà ça vaut plus le coup:
https://toutpourlejeu.com/fr/cubes-et-jetons-carre/744-cubes-en-bois-08-cm-8x8x8-mm-lot-20.html

**Comment by dracdrac** [comment]
mais je me dis que cest pas mal que ce jeux ça soit un peu du craft

**Comment by LeonLenclos** [comment]
(pour simplifier, je compte qu'il nous faut 200 pions)

https://toutpourlejeu.com/fr/jeton-rond-et-cylindre/515-pions-jetons-bois-15-x-4-mm-lot-20-pour-jeux-0659436657052.html reviendrai en gros à moins de 9,8€ par boite

https://toutpourlejeu.com/fr/des-neutres-a-personnaliser/373-cubes-en-bois-1-cm-10-x-10-x-10-mm-lot-20.html -> 9,6 € par boite

https://toutpourlejeu.com/fr/pions-et-jetons-encastrables/3300-1000-pions-cubes-emboitables-1-cm-clipsables-5415124200932.html -> 7,68€ par boite

https://toutpourlejeu.com/fr/jeton-rectangle-et-batonnet/3433-100-buchettes-5x5x25-mm-10-couleurs-pions-en-bois-pour-jeu.html -> 6,50€

**Comment by dracdrac** [comment]
ça peut etre rigolo les jetons encastrables
