### ISSUE TITLE
symboles spéciaux

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/pollos-para-todos#3]
Le symbole à uttiliser pour couronne c'est lui : `₵`

Pour les symboles de carte, je pense que le mieux est de  directement integrer les images dans le html

```
<img src="img/action.png"/>
<img src="img/evennement.png"/>
<img src="img/persistante.png"/>
<img src="img/unique.png"/>
```

**Comment by dracdrac** [comment]
ok
