### ISSUE TITLE
Egalité?

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/pollos-para-todos#4]
que se passe t-il s'il y a égalité entre ceux qui ont le plus de point au décompte final?
=>un tour supplémentaire pour ceux qui sont à égalité? en enlevant les pions des autres joueurs?
=>les élections sont reportées au lendemain, n'importe quel joueur peut encore gagner

**Comment by LeonLenclos** [comment]
Les peuvent être bien, la première option ça fait vraiment "second tour d'elections" c'est pas mal. Mais c'est un peu chiant pour les autres joueurs...

**Comment by dracdrac** [comment]
Bon après c'est super rare comme cas
Je pense qu'on peut faire le second tour d'elections, et vu qu'il n'y aura que 2 joueurs ça ira très vite

**Comment by LeonLenclos** [comment]
ok
