### ISSUE TITLE
Slogan

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/pollos-para-todos#6]
ça pourrait être cool d'avoir une petite phrase genre entre le slogan et le sous-titre. Un peu une phrase d'accroche. Comme "attrapez les tous" pour les pokemon.

**Comment by dracdrac** [comment]
OK
prenez le pouvoir
faites les bien frire
et mon cul c'est du téflon?

**Comment by LeonLenclos** [comment]
Prenez le pouvoir

**Comment by LeonLenclos** [comment]
Super
