### ISSUE TITLE
map

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/pollos-para-todos#7]
plusieurs pensées:
-souligner le nom des zones

-mettre un emplacement pour mettre les cartes evenement et action avec leurs défausses
_peut être que ça prend trop de place sur la map et que ça obligera à rapetisser la map?_

-mettre un décompte des jours
_nous on à l'habitude de compter les cartes evenement mais cest vrai que parfois on se rend pas compte qu'il ne reste qu'un ou deux jours_

**Comment by LeonLenclos** [comment]
Yes
Yes
Yes

**Comment by LeonLenclos** [comment]
fait, fait, fait
