### ISSUE TITLE
Impression cartes de jeu

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/pollos-para-todos#9]
j'ai tenté d'imprimer une feuille, problèmes:
- la derniere ligne qui correspond au fond des cartes du bas ne s'est pas imprimée
- les traits verticaux du milieux pour séparer les cartes sont plus épais que ceux du contour et ceux qui sont horizontaux. Les traits plus fins sont trop fins: il faudrait mettre la meme épaisseur partout car c'est plus pratique pour découper quand les traits sont plus épais
- n'hésites pas à m'appeler si je ne suis pas tres clair au 07******62

**Comment by LeonLenclos** [comment]
Ok et la taille de la typo ça passe ?

**Comment by dracdrac** [comment]
Oui je crois

**Comment by LeonLenclos** [comment]
donc c'est réglé
